name: Docker Compose CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-lastest

    steps:
    - name: ğŸ“« Checkout repository
      uses: actions/checkout@v3

    - name: ğŸ”‘ Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: pannawitmahacharoensiri
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: ğŸ› ï¸ Build and tag Docker images
      run: |
        docker compose -f docker-compose.yml build
    
    - name: ğŸ‹ Tag & Push Backend image
      run: |
        docker tag todo101-todo-backend pannawitmahacharoensiri/todo-backend:lastest
        docker push pannawitmahacharoensiri/todo-backend:lastest

    - name: ğŸ‹ Tag & Push Frontend image
      run: |
        docker tag todo101-todo-frontend pannawitmahacharoensiri/todo-frontend:lastest
        docker push pannawitmahacharoensiri/todo-frontend:lastest


